version: '3.8'

services:

  db:

    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=showcase_db
    ports:

      - "5434:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data